# Generated by Django 4.0.3 on 2022-04-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['title', 'slug'], 'verbose_name': 'Maqala', 'verbose_name_plural': 'maqalalar'},
        ),
        migrations.RemoveField(
            model_name='posts',
            name='email',
        ),
        migrations.AddField(
            model_name='posts',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
