# Generated by Django 4.0.2 on 2022-05-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_posts_options_remove_posts_email_posts_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='picture',
            field=models.ImageField(blank=True, upload_to='posts/'),
        ),
    ]
