# Generated by Django 4.0.2 on 2022-05-03 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_posts_pictute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='picture',
            new_name='picture',
        ),
    ]
