# Generated by Django 4.0.2 on 2022-05-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_pictute_posts_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['name', 'lastname'], 'verbose_name': 'Тіркелу', 'verbose_name_plural': 'Тіркелу'},
        ),
        migrations.AddField(
            model_name='posts',
            name='url',
            field=models.URLField(default=1, max_length=255, verbose_name='URLS'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='picture',
            field=models.ImageField(default='default value', upload_to=''),
        ),
    ]
