# Generated by Django 4.0.2 on 2022-05-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_contact_alter_posts_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='is_published',
            field=models.BooleanField(default='True', verbose_name='YES?NO'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Name_ANIME'),
        ),
    ]
